apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: ldapidp 
    mappingMethod: claim 
    type: LDAP
    ldap:
      attributes:
        id: 
        - dn
        email: 
        - mail
        name: 
        - cn
        preferredUsername: 
        - uid
      bindDN: "uid=admin,cn=users,cn=accounts,dc=lab,dc=integrate,dc=zone"
      bindPassword: 
        name: ldap-secret
      ca: 
        name: ca-config-map
      insecure: false
      url: "ldap://idm.lab.integrate.zone/cn=accounts,dc=lab,dc=integrate,dc=zone?uid" 